name: Prisma Cloud Compute Image Scan

on: [push, pull_request]

env:
  IMAGE_NAME: ${{ github.repository }}:${{ github.sha }}

jobs:
  # Jobs are ran independently from each other, so build and scan needs to be in a single job.
  build-and-scan:
    name: Build and scan image
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        # Defaults are sufficient generally
        # https://github.com/actions/checkout#usage

      - name: Download twistcli from the Prisma Cloud Compute Console
        run: |
          curl --user jongwoon:1234 --output ./twistcli a912b3b1b642f474e9d8c7e3c6a1ab94-713768258.ap-northeast-2.elb.amazonaws.com:8083/api/v1/util/twistcli
          chmod a+x ./twistcli
          pwd
          

      - name: Build the image
        run: sudo docker pull ubuntu:latest 
             

        

      - name: Scan the image
        run: /home/ubuntu/prisma_cloud
/twistcli images scan --address https://a912b3b1b642f474e9d8c7e3c6a1ab94-713768258.ap-northeast-2.elb.amazonaws.com:8083 --user jongwoonCI --password 1234 --details ubuntu:latest
