name: Prisma Cloud Compute Image Scan
# test 12
on: [push, pull_request]

env:
  IMAGE_NAME: ${{ github.repository }}:${{ github.sha }}

jobs:
  # Jobs are ran independently from each other, so build and scan needs to be in a single job.
  build-and-scan:
    name: Build and scan image
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        # Defaults are sufficient generally
        # https://github.com/actions/checkout#usage

      - name: Download twistcli from the Prisma Cloud Compute Console
        run: |
          curl --user ${{ secrets.PCC_USER }}:${{ secrets.PCC_PASS }} --output ./twistcli ${{ secrets.PCC_CONSOLE_URL }}/api/v1/util/twistcli
          chmod a+x ./twistcli
          pwd
          cd /home/runner/work/jwjw/jwjw
          

      - name: pull the image
        run: docker pull ubuntu:latest

      - name: cd /home/runner/work/jwjw/jwjw
        run: cd /home/runner/work/jwjw/jwjw

      - name: pwd 
        run: pwd

      - name: ls -al
        run: ls -al

      - name: Scan the image
        run: ./twistcli images scan --address ${{ secrets.PCC_CONSOLE_URL }} --user ${{ secrets.PCC_USER }} --password ${{ secrets.PCC_PASS }} --details ubuntu:latest
